name: CI

on:
  push:
    branches:
      - main

jobs:
  run-terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ''

      - name: Setup Terraform
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: 1.10.5

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform plan
        run: terraform plan
        env:
          TF_VAR_PROFILE: rodrigofontesdev
          TF_VAR_REGION: us-east-1

      - name: Terraform apply
        run: terraform apply -auto-approve
